-- #selfhost-linked-issue-gate-drift: repository_settings.linked_issue_gate_mode was persisted as 'block'
-- by migration 0023 (its initial ADD COLUMN default) and migration 0025 (a since-superseded "restore"
-- backfill that flipped any 'advisory' row to 'block' for repos with gate_check_mode='enabled'), even
-- though missing a linked issue is only ever supposed to be advisory unless a maintainer explicitly opts
-- into blocking. The application-level fallback (src/db/repositories.ts) and every documented default
-- (.gittensory.yml.example, docs.tuning.tsx, the settings API schema) already say 'advisory' -- only the
-- persisted column value drifted.
--
-- #gate-review-2727 round 1: require_linked_issue = 0 alone does NOT prove drift. linkedIssueGateMode and
-- requireLinkedIssue are independently settable (the maintainer settings UI exposes them as a separate
-- dropdown and toggle; both PUT .../settings and the internal settings route accept linkedIssueGateMode on
-- its own), so a maintainer can genuinely choose 'block' while leaving requireLinkedIssue off. No column on
-- this row records which field a maintainer last touched, so per-field intent can't be recovered by itself.
--
-- #gate-review-2727 round 2: an earlier draft used `updated_at = created_at` ("never written to since
-- creation") as the drift signal, anchored implicitly on the row's OWN creation time. That missed rows last
-- written before migration 0023 even added the column (provably drift too, just not "never written")
-- AND, the opposite failure mode, could clobber a repo whose very FIRST-EVER settings save explicitly chose
-- 'block' (upsertRepositorySettings sets createdAt and updatedAt to the same instant on that single INSERT,
-- so a genuine first-save opt-in is indistinguishable from untouched drift under that condition alone).
--
-- What CAN be proven: updated_at is bumped on every write through upsertRepositorySettings
-- (src/db/repositories.ts) -- the ONLY code path that ever inserts or updates this row, always through
-- Drizzle, always with an explicit resolved value for this column (never omitted, so the raw column-level
-- default below never fires through it) -- so updated_at is exactly "the last instant any application code
-- touched this row, insert or update alike". linked_issue_gate_mode did not exist as a column, and therefore
-- could not have been part of ANY resolved settings value, before migration 0023 was deployed at commit
-- 66e4dd6b (2026-06-05T14:01:39-06:00 = 2026-06-05T20:01:39Z; this repo auto-deploys `wrangler d1 migrations
-- apply --remote` on every merge to main, so the merge commit time is a same-day, conservatively-early proxy
-- for the real remote apply time -- true apply is always slightly AFTER this timestamp, never before, so an
-- inclusive upper bound here can only under-select rows, never wrongly include one written after the column
-- existed). A row whose updated_at is at or before that instant has therefore NEVER been written to by any
-- application code since the column started existing, under ANY value -- its current 'block' can only be
-- the byproduct of migration 0023's column-add default or 0025's later blanket flip, never a maintainer's
-- resolved choice. That single condition subsumes the "never touched since creation" case too: a row with no
-- write at all still has its ORIGINAL creation timestamp as its updated_at, which for any row old enough to
-- predate 0023 is at-or-before the cutoff by construction.
--
-- A row with updated_at after that cutoff has been through at least one real settings write (its own
-- creation or a later update) since the column existed and is left alone, even though some of those may also
-- be untouched drift this migration can no longer safely reach -- a maintainer stuck with a leftover 'block'
-- default can flip it from the settings UI. Leaving that row alone is the safe failure mode; silently
-- downgrading a real 'block' opt-in -- first-save or later -- to advisory is not.
--
-- The raw SQLite column-level DEFAULT on linked_issue_gate_mode itself (set to 'block' by migration 0023's
-- `ADD COLUMN ... DEFAULT 'block'`) is intentionally left as-is here rather than rebuilt to 'advisory': SQLite
-- has no ALTER COLUMN SET DEFAULT, so changing it requires a full create-copy-drop-rename table rebuild --
-- an operation with no precedent anywhere in migrations/ and real operational risk for a table this central,
-- for a column-level default that no live code path ever reaches (upsertRepositorySettings is the only
-- writer, and it always resolves and supplies an explicit value; see
-- test/unit/schema-timestamp-defaults.test.ts, which pins that even an omitted-field Drizzle insert resolves
-- via the schema.ts default, never this raw column default).
UPDATE repository_settings
SET linked_issue_gate_mode = 'advisory'
WHERE linked_issue_gate_mode = 'block'
  AND require_linked_issue = 0
  AND updated_at <= '2026-06-05T20:01:39.000Z';
